### ISSUE TITLE
Manual install instructions or apt package with no deps?

### ISSUE THREAD

**Issue by mgsloan** [Gekkio/gnome-session-xmonad#10]
Hey, nice project!  I'm curious what the most straightforward way would be to manually install these session files.

I use stack to build my xmonad - I do not want to install ghc / xmonad / etc from apt.  There is a symbolic link from `~/.local/bin/xmonad` to the built xmonad, and `~/.profile` adds that to `PATH`.

It would be great to have manual setup instructions for a setup like that.  I tried the PPA but it wanted to install 1GB worth of stuff I don't want - I don't want to have a global GHC install - and `xmonad` / `xmonad-contrib` are submodules of my xmonad configuration repo (https://github.com/mgsloan/mgsloan-dotfiles).  Even better than manual setup instructions would be a PPA package which has no dependencies and just installs the few files that setup the gnome-session login provided that xmonad is on the user's PATH.  (not sure if .profile runs before the session stuff, so that might be problematic)

Thanks!

**Comment by ntc2** [comment]
@mgsloan (Hi!) not sure it was the "most straightforward" way, but I also wanted to use this Gnome + XMonad config without bringing in a whole Ubuntu-manged GHC ecosystem and I ended up with this: https://github.com/ntc2/gnome-session-xmonad/blob/ubuntu/bionic/minimal-install.sh. Note that I'm using `apt-get install --no-install-recommends xmonad` to install the Ubuntu `xmonad` package (we need some of it's `.desktop` files) without bringing in the Ubuntu GHC ecosystem. The same trick doesn't work with the `gnome-session-xmonad` package you filed the issue against, so added it as a submodule and just manually copy over the two files it provides in my `minimal-install.sh`, linked above.

Re your question about Gnome getting the `xmonad` binary from the user's `PATH`, in my experience Gnome starts the Xsession with a very minimal `PATH` that doesn't include the `PATH` extensions added by the user's shell startup files. In the past I've worked around this by changing `Exec=xmonad` to `Exec=zsh -c xmonad` (I use ZSH, and writing `Exec=$SHELL -c xmonad` doesn't work) in the `.desktop` files that execute `xmonad`. You'll also need to find an eliminate any `TryExec=xmonad` lines, since `TryExec=<cmd>` means "fail if `<cmd>` is not on `PATH`".

Poking around a little, I think you'd have to change `Exec=xmonad` in the `/usr/share/applications/xmonad.desktop` provided by the `xmonad` package, and remove `TryExec=xmonad` in the `gnome-xmonad.desktop` provided by the `gnome-session-xmonad` repo.

But it seems actually getting `xmonad` from the `PATH` is unnecessary, since after you've run `xmonad --recompile` once it seems that what `xmonad` really runs is the `~/.xmonad/xmonad-x86_64-linux` (or whatever on your machine), so just using the `/usr/bin/xmonad` provided by the `xmonad` package suffices. Alternatively, if that doesn't work for some reason, you could just copy your local `xmonad` binary to `/usr/bin/xmonad` the first time, and then rely on `xmonad --recompile`.

I looked at your dot-files repo a bit but I don't understand how you're building `xmonad` (I see you have an `xmonad` submodule, but I couldn't find an `.xmonad/xmonad.hs`). My current setup, including how it uses this `gnome-session-xmonad` repo, is here: https://github.com/ntc2/conf/tree/master/dot.xmonad.

**Comment by mgsloan** [comment]
@ntc2 Hey!  Yeah, I wanted to use `~/env` instead of `/.xmonad`.  Not sure why exactly, I think it was to reduce the number of directories checked into my dotfiles repo.  Otherwise, it's a pretty straightforward use of the `build` file + submodules for xmonad + stack.  The modified directory works due to these lines in my `.profile`:

```
export XMONAD_DATA_DIR="$HOME/env"
export XMONAD_CACHE_DIR="$HOME/env"
export XMONAD_CONFIG_DIR="$HOME/env"
```

Perhaps things weren't working because these weren't being applied before running my xmonad.  It probably isn't worth it to do this change of directory.

Thanks for putting effort into looking into this.  Unfortunately, the xmonad + flashback seems to be super unstable for me.  An assortment of problems: it exits back the session login after a few minutes, doesn't have a desktop background, and `keynav` crashes saying the window manager doesn't support a "current window".

My current gross thing of starting vanilla ubuntu + opening a terminal + typing `xmonad --replace` works pretty well.  I also like having a terminal open that contains stdout from xmonad and its child processes. 
 Perhaps I will just automate running `xmonad --replace` in a terminal as a startup application..

**Comment by mgsloan** [comment]
Running `gnome-session-properties` and adding an autostart that runs `urxvt -e sh -c "/home/mgsloan/.local/bin/xmonad --replace"` seems to work pretty well.  Hacky as hell, but nicer than doing it manually every restart.  Thanks for reminding me to revisit this!

**Comment by ntc2** [comment]
A few questions:

1) what version of Ubuntu are you using? I'm using 18.04.

2) how were you starting the unstable "xmonad + flashback" session? Note that if you use this `gnome-session-xmonad` package (either with my `minimal-install.sh` script or by installing the PPA), you'll have two xmonad entries in the login manager session list. One says "GNOME + XMonad" and one says "GNOME Flashback (Xmonad)". You need to choose the "GNOME + XMonad" one, since the other one (provided by `xmonad` package) is broken.

3) if you start a "Gnome Flashback (metacity)" session, do you have the any of the same instability?

Re the not having a desktop background, I had a similar problem earlier after I had run some command as root when I shouldn't have, and so root owned some files in my home dir and the permissions were too restrictive. I think I used something like

```
 find ~ \! -user `whoami`
```

to find the suspect files, and then did ``chown -R `whoami`:`` on them.

**Comment by mgsloan** [comment]
@ntc2 Yep I'm also on 18.04, Bionic and indeed ran the xmonad + flashback session.  I did not run your script directly, though.  Instead:

* I modified the `.desktop` file to instead have a path to xmonad in my home dir.  Since xmonad does start, that modification appears to have worked correctly.

* I ran `sudo apt install gnome-flashback` to install the flashback session

* Then I just ran the `sudo install` lines to copy the .desktop and .session files.

Particularly, I did not install the xmonad package and did not install the deps (I probably already have them)

Also, one thing I noticed is that I needed to do a full restart before the configuration would show up on the login screen.

Running a vanilla flashback session, and then doing `xmonad --replace` mostly works - doesn't have the issue I encountered with the xmonad + flashback session, but I also saw some other weird behavior there.  Specifically, `M-<Space>` to switch layout didn't work!  I can't think of any plausible explanations for that.

I appreciate you iterating further on this.  I'm actually reasonably content with the hack for now, certainly beats what I was doing before.  I suppose it might be good to figure out what's going on so that others don't encounter it..  Hmm!

**Comment by ntc2** [comment]
Since you didn't install the `xmonad` package, that might be the problem. Note that it provides more relevant `.desktop` files, e.g. `/usr/share/applications/xmonad.desktop` (https://packages.ubuntu.com/bionic/i386/xmonad/filelist).

No worries if you're tired of working on this, but if you aren't, I'd be curious if doing

```
sudo apt-get install --no-install-recommends xmonad
sudo install --mode=0644 /home/mgsloan/.local/bin/xmonad /usr/bin/xmonad
```

and then rebooting and choosing the "XMonad + Gnome" session works.

You can easily reverse this with

```
sudo apt-get purge xmonad
sudo rm /usr/bin/xmonad
```

**Comment by mgsloan** [comment]
I figured it might be due to out of date packages, so I foolishly did a `sudo apt upgrade` and updated 400 packages.  Unfortunately, my machine failed to boot after this, IIRC some lvm error after boot.  Googling around revealed it may be a kernel bug, but using an older kernel version didn't work.  So, anyway, I used this as an excuse to install a fresh ubuntu.  Glad to have a good reason to do this, because finally my root partition is on software raid 0 of nvme ssds!  My setup notes are here - https://github.com/mgsloan/mgsloan-dotfiles/blob/master/env/setup.md

This time I ran `minimal-install.sh` directly, but still encountered the same behavior.  I used `journalctl --reverse` after the crash, and found the following in the log (in reverse order):

```
Dec 24 16:38:02 treetop systemd[1521]: gnome-session.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 16:38:02 treetop gnome-session-binary[5850]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Dec 24 16:38:02 treetop gnome-session[5850]: gnome-session-binary[5850]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Dec 24 16:38:02 treetop gnome-session-binary[5850]: Unrecoverable failure in required component xmonad.desktop
Dec 24 16:38:02 treetop gnome-session-binary[5850]: WARNING: Application 'xmonad.desktop' failed to register before timeout
Dec 24 16:38:02 treetop gnome-session[5850]: gnome-session-binary[5850]: WARNING: Application 'xmonad.desktop' failed to register before timeout
Dec 24 16:37:30 treetop xmonad.desktop[6073]:   Current serial number in output stream:  73
Dec 24 16:37:30 treetop xmonad.desktop[6073]:   Serial number of failed request:  73
Dec 24 16:37:30 treetop xmonad.desktop[6073]:   Resource id in failed request:  0xb1ba0140
Dec 24 16:37:30 treetop xmonad.desktop[6073]:   Major opcode of failed request:  14 (X_GetGeometry)
Dec 24 16:37:30 treetop xmonad.desktop[6073]: X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
Dec 24 16:37:30 treetop xmonad.desktop[6073]: Your windowmanager claims not to support _NET_ACTIVE_WINDOW, so the attempt to query the active window aborted.
```

The most crucial line looks like `gnome-session-binary[5850]: WARNING: Application 'xmonad.desktop' failed to register before timeout`.

The error about `_NET_ACTIVE_WINDOW` is due to me attempting to use `keynav`, which for my config starts out querying the bounds of the current window.

I'm guessing these two things are related.  My vague intuition is that xmonad is not properly registering itself as a window manager, or something along those lines.  Perhaps my use of the gnome config stuff is wrong - I don't really use much of the integration with gnome at all (no top bar).

Will look into it further

**Comment by mgsloan** [comment]
@ntc2 Seems like your https://github.com/ntc2/conf/blob/master/dot.xmonad/startup-hook.sh is a potential fix.  Unfortunately, it doesn't seem to resolve the problem for me (and I've verified that it's getting run).  Curious!

I am somewhat interested in getting this stuff working, since before it crashes, some things do seem a fair bit snappier.  Not 100% sure if it actually is, though.

**Comment by ntc2** [comment]
Ouch! Yeah, the only thing I know about "failed to register" errors is that `startup-hook.sh` script you found :/

**Comment by Gekkio** [comment]
Huh, I thought the `xmonad` package had a normal dependency on the GHC packages. This changes things a bit...

I think I'll make `libghc-xmonad-contrib-dev` a recommended dependency of `gnome-session-xmonad` because there's no absolute reason why the GHC ecosystem should always be pulled along with it. My original justification for the dependency in `gnome-session-xmonad` was the fact that the default binary in the `xmonad` package won't work in a gnome session because it lacks the necessary gnome-specific configuration. So you always need a custom configuration and the contrib package to compile it to have a working setup. But if you provide your own xmonad using some other mechanism, it's possible to have a working session without the GHC packages.

So, I'll make it a recommended dependency, so you can just install `gnome-session-xmonad` and `xmonad` without any GHC packages.

@mgsloan, you are probably replacing something from `gnomeConfig` (e.g. manageHooks maybe) when you should be appending/prepending. There's a layered chain of config (gnome config, ewhm config, desktop config, base xmonad config) and if you replace some config property and ignore the stuff the chain has put there, you'll end up having various problems. It's possible to make it work, but you need to go through the entire chain of configs and replicate the necessary functionality yourself.

I can point out at least these two things which are in my experience mandatory for a sane desktop:

* `startupHook` in `gnomeConfig`: <https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Config/Gnome.hs#L46>. This is absolutely necessary or gnome-session will kill your session after a timeout.
* everything in `ewmh`: <https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Hooks/EwmhDesktops.hs>. It's possible to have a mostly working desktop without this, but many applications rely on ewmh behaviour and you can get random breakage. I remember having problems with Java apps and full-screen apps before I set up ewmh stuff properly in my config.

As an additional bonus, sometimes the order matters and you can have various problems even if you have the right hooks but they are in the wrong order.

**Comment by mgsloan** [comment]
@Gekkio Ah, yes, I think you're right!  I was overriding `startupHook` which renders the use of `gnomeConfig` entirely moot.

Surprisingly, just using the `XMonad` session works quite well (none of the problems I described above with the other config), even without the proper gnome startup hook, only ewmh stuff.

I finally have a proper login session for xmonad :+1: , so considering this resolved.  Thanks for the help @ntc2 and @Gekkio !
